export const SET_FILTER_CRITERIA = 'SET_FILTER_CRITERIA';
export const REMOVE_CRITERIA_FROM_FILTER = 'REMOVE_CRITERIA_FROM_FILTER';

export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';

export const SORT_BY_LOWEST_PRICE = 'SORT_BY_LOWEST_PRICE';
export const SORT_BY_HIGHEST_PRICE = 'SORT_BY_HIGHEST_PRICE';
export const SORT_BY_HIGHEST_RATE = 'SORT_BY_HIGHEST_RATE';
export const SORT_BY_NEWEST = 'SORT_BY_NEWEST';
export const SORT_BY_DISCOUNT = 'SORT_BY_DISCOUNT';
export const SORT_BY_FEATURED = 'SORT_BY_FEATURED';
